# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: RWX
subtitle: Read Write Execute
description: This is a written down account of my journey toward coding Zen
author: Nana Adane
email: info@nanaadane.com
language: en

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.nanaadane.com/
root: /
permalink: :year/:month/:day/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
permalink_defaults:

# Directory
source_dir: source
public_dir: public

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: randoms
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 2
category: 2
tag: 2

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
server_ip: localhost
logger: false
logger_format: dev

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMM D YYYY
time_format: H:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Disqus
disqus_shortname: readwriteexecute

# Extensions
## Plugins: https://github.com/hexojs/hexo/wiki/Plugins
## Themes: https://github.com/hexojs/hexo/wiki/Themes
## https://github.com/probberechts/hexo-theme-cactus
theme: cactus

theme_config:
  colorscheme: white
  nav:
    home: /
    about: /about/
    Writing: /archives/
    projects: http://github.com/v3rse
  social_links:
    github: https://github.com/v3rse
    twitter: https://twitter.com/NanaOAdane
    linkedin: https://www.linkedin.com/in/nanaadane/
    # mail: mailto:nanaofosuheneadane@gmail.com
  tags_overview: true
  posts_overview:
    show_all_posts: true
    # post_count: 5
  logo:
    enabled: true
    width: 50
    height: 50
    # url: /images/logo.png
    gravatar: true
  favicon:
    desktop:
      # url: /images/favicon.ico
      gravatar: true
    android:
      # url: /images/favicon-192x192.png
      gravatar: true
    apple:
      # url: /images/apple-touch-icon.png
      gravatar: true
  gravatar:
    email: nanaofosuheneadane@gmail.com
  disqus:
    enabled: true
    shortname: readwriteexecute

sitemap:
  path: sitemap.xml

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:v3rse/v3rse.github.io.git
